### ISSUE TITLE
This demo is good. I also provide a bpg coder for SDWebImage

### ISSUE THREAD

**Issue by dreampiggy** [SDWebImage/SDWebImageProgressiveJPEGDemo#1]
@bpoplauschi  This JPEG custom coder looks good. Although that Apple's JPEG use that hardware DSP(digital signal processor) to decoder JPEG and is 4x faster than libjpeg and 2x than libtjpeg-urbo. So most case it's recommaned to use that built-in JPEG Coder. Unless you need some extra feature that now open to public API like this native-Progressive-JPEG support. (Apple's implementation need specify JPEG format but not normal JPEG. See our demo)

I also create a demo with that [BPG image format](https://bellard.org/bpg/). The repo is here: https://github.com/dreampiggy/SDWebImageBPGCoder

This is a naive support and just use that wrapper [HCImage-BPG](https://github.com/chuganzy/HCImage-BPG). It works well but I can remove this dependency and implement myself if this toy is really useful for some people :)

And I suggest, maybe someday we can seperate these coders to one repo(Something like `SDWebImageThirdPartyCoders` with some subspec like `BPG`, `FLIF` and so on), or use github organization to manage them (But this seems a long way to go), we create cocoapods spec or even subspec for that like I do. Then the demo project can be placed into that spec's demo project. So that it's easy for user to intergrate in.  :)

**Comment by bpoplauschi** [comment]
@dreampiggy Hi there :)

- **Progressive JPEG**: I don't have a lot of experience with this, but from what I know the default Apple coder doesn't fully support the Progressive JPEG. But a very good friend @mihaigpm has more experience so I have asked him to come help us here. You are probably right about performance, but we need to see if DSP can properly handle progressive JPEG. Actually, talking to him about integrating Concorde with SDWebImage reminded me how much we need to be able to plugin coders. And we can :) Especially since you started that big refactoring.
- **BPG**: I just saw that project pop up on your Github and it's nice to see this easy ability to write reusable sharable coders for our lib. This is now a **differential** from our "competitors" :) 
- **using HCImage-BPG**: I would not remove the dependency unless it's really necessary or we can improve it a lot. Let that project be maintained by people with experience in that area, we will focus on ours.
- **Organise projects**: that is a very good point which I also considered. I've previously talked to Olivier Poitrey (the creator and owner of SDWebImage, mister "rs" in person) on a few occasions, but he's not willing to move the project to an organisation. What we can do is use this organization [SDWebImage](https://github.com/SDWebImage) I created some time ago and re-activated it. We can move all those projects and the ones related there.

**Comment by bpoplauschi** [comment]
@dreampiggy I've just moved my demo from bpoplauschi/SDWebImageProgressiveJPEGDemo to [SDWebImage/SDWebImageProgressiveJPEGDemo](https://github.com/SDWebImage/SDWebImageProgressiveJPEGDemo). You can do the same once you accept the invitation into the organization.

**Comment by dreampiggy** [comment]
@bpoplauschi I understand your idea. I joined the orginaization and move this demo project into the https://github.com/SDWebImage/SDWebImageBPGCoder

**Comment by dreampiggy** [comment]
@bpoplauschi I agree that we should make our coders clean and let third-party lib work the mosts of work, we just build a wrapper and add the feature which is not supported. That HCImage-BPG decoder looks good and I'll keep it. But unfortunately it lacks of encoding support. But since rare case we use that encoding(currently only `write image without data to disk` and that `scaled down and set image data` method). If I have extra time, I can try to implement one or open a PR to the original repo. (Because maybe I enjoy writing this image-coding-related code) :)

**Comment by bpoplauschi** [comment]
@dreampiggy sounds good. If you like writing image-coding-related code, then do it :) now we have an organization where we can put demos and other useful projects. I just wanted to way we don't want that into the main project.

**Comment by bpoplauschi** [comment]
@rs we've reactivated the [SDWebImage organization](https://github.com/SDWebImage) for related projects like coders, demos, ...
We've refactored the way decoding/encoding works so that we support some built-in coders (like IOImage, GIF, WebP) and users can easily add their own.

**Comment by dreampiggy** [comment]
Seems long time passed. I already upload the BPG coder [SDWebImageBPGCoder](https://github.com/SDWebImage/SDWebImageBPGCoder) to Cocoapods long time ago.

---

Well, talke about one interestring thing. 😃 Recently I found a open-sourced HEIF codec called [libheif](https://github.com/strukturag/libheif), which was written in C/C++. Though it's really new and during quickly development. I try to make it works and create on [SDWebImageHEIFCoder](https://github.com/SDWebImage/SDWebImageHEIFCoder). You can see it successfully run on iPhone Simulator.

This HEIF coder can now **decoding & encoding** HEIF still/single images. And it support heic brand as well as mif1 brand ! (Beyond Apple). Which more importantlly, since it's a software codec, it can support from iOS 8+/macOS 10.10+ without any dependency of Apple's Image/IO built-in framework.

This may help someone who need to keep compatibility or need support software-based HEIF encoding. For more information, maybe check that repo is better :)

**Comment by bpoplauschi** [comment]
Closing this issue - good conversation starter for all our dedicated repos
